version: '3.8'

services:
  fastapi-app:
    build: .
    container_name: fastapi-container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./static/images:/app/static/images
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "python -m app.scripts.bulk_insert && 
             uvicorn app.main:app --host 0.0.0.0 --port 8000"