version: '3.8'

services:
  fastapi-app:
    build: .
    container_name: fastapi-container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./static/images:/app/static/images
    environment:
      - PYTHONUNBUFFERED=1